---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-ns
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-ns-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev
roleRef:
  kind: Role
  name: admin-ns
  apiGroup: rbac.authorization.k8s.io
